# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run tests for the Swift package"
  lane :run_package_tests do
    Dir.chdir("..") do
      # Run tests for the Swift package using xcodebuild
      sh "xcodebuild test -scheme some-codable-swift -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest'"
    end
  end
end
